favicon / OGP設定（仮）
t0m0120/IshikawaTakidashiMap pull request #10
Opened 2024-01-05 14:42 UTC by HirotoTsujii

### 概要
・issue(#2)を受け、favicon / OGP設定 の追加を行いました。
・設定している画像は、bing(DALLE3)を使い生成したもので、よりよいものがあれば差し替えてください。
（プロンプトはfavicon for japan lifeline map application simply）

### 変更内容
・app/layout.tsx の一部を定数化しました。（文言など）
・画像ファイルを追加しました。

### 参考サイト等
・https://zenn.dev/temasaguru/articles/641a10cd5af02a

### その他
・旧faviconはold_favicon.icoという名前に変更しています。
・faviconは、app配下のfavicon.icoを差し替えることで変更可能です。
・OGP画像は、app配下のopengraph-image.jpgを差し替えることで変更可能です。

### 行った動作確認
・faviconの確認
・OGP設定の確認はlocalでの確認ができておりません。また、設定の方法が良くない可能性もあります。（urlなど）

2024-01-06 08:25 UTC, t0m0120 requested changes
@HirotoTsujii

OGP周りの修正と、画像の追加などありがとうございます！ 🎉  
1点だけ気になった箇所をコメントしたので確認をお願いします 🙇 


下記のChrome拡張でHead周りを確認してみたところ、localhost上で問題なさそうでした！ 💪 

https://chromewebstore.google.com/detail/localhost-ogp-%E3%83%81%E3%82%A7%E3%83%83%E3%82%AB%E3%83%BC/gcbnmkhkglonipggglncobhklaegphgn?hl=ja&pli=1

2024-01-06 08:25 UTC, t0m0120 commented on app/layout.tsx
> +  openGraph: {
👍

2024-01-06 08:25 UTC, t0m0120 commented on app/layout.tsx
> +const url = "https://ishikawatakidashimap.pages.dev/Sentou"; // 本番URL
TopのURL(`https://ishikawatakidashimap.pages.dev/`)のほうが良さそうかと思いました！

2024-01-06 09:30 UTC, HirotoTsujii commented on app/layout.tsx
> +const url = "https://ishikawatakidashimap.pages.dev/Sentou"; // 本番URL
ありがとうございます。その通りですね。
確認不足でした🙇‍♀️

2024-01-06 10:32 UTC, HirotoTsujii commented
変更を行いました！

2024-01-07 04:56 UTC, t0m0120 approved these changes
@HirotoTsujii 
修正ありがとうございます 🙇 
マージします！

2024-01-07 04:56 UTC, merged